"""Run SeawaterPolynomials.jl (Oceananigans) to produce truth for the idealized
Roquet equations of state.

xeos's six idealized second-order Roquet backends (``roquet-linear``,
``roquet-cabbeling``, ``roquet-cabbeling-thermobaricity``, ``roquet-freezing``,
``roquet-second-order``, ``roquet-simplest-realistic``) are transcriptions of the
``RoquetSeawaterPolynomial(:X)`` coefficient sets in CliMA's SeawaterPolynomials.jl
-- the package Oceananigans uses. Until now they had no numeric reference (only one
hand-computed value each). This generator evaluates the *actual Julia package* on
the validation grid, giving them machine-precision truth straight from source.

It writes a small Julia driver that, for each coefficient set, builds a
``RoquetEquationOfState`` and evaluates ``ρ`` (total density), and the analytic
``thermal_sensitivity`` (= -∂ρ/∂Θ) and ``haline_sensitivity`` (= ∂ρ/∂Sᴬ); alpha and
beta are these divided by ρ -- matching xeos's analytic derivatives. Geopotential
height is ``Z = -p`` (sea pressure in dbar ≈ depth in m, negative downward), the
same convention xeos's ``_roquet_idealized.py`` uses.

Two published-coefficient check values (Roquet 2015, Table 3) gate the output
before it is trusted -- one at Z=0 and one at Z=-1000 dbar, so a mis-wired driver
(swapped Θ/Sᴬ, wrong Z sign) fails loudly. Requires ``julia`` with the
SeawaterPolynomials package available; ``Pkg.add`` is run on first use.
"""

import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
_DRIVER = os.path.join(HERE, "_seawaterpolynomials_driver.jl")  # gitignored

# Map xeos backend id -> SeawaterPolynomials.jl coefficient-set symbol.
COEFFICIENT_SETS = {
    "roquet-linear": "Linear",
    "roquet-cabbeling": "Cabbeling",
    "roquet-cabbeling-thermobaricity": "CabbelingThermobaricity",
    "roquet-freezing": "Freezing",
    "roquet-second-order": "SecondOrder",
    "roquet-simplest-realistic": "SimplestRealistic",
}

# Independent checks from Roquet (2015) Table 3 coefficients, at Θ=10, Sᴬ=35.
_CHECK_LINEAR_Z0 = 1049.8379999999997  # :Linear, Z=0
_CHECK_CABTHERMO_Zm1000 = 1050.2024899999997  # :CabbelingThermobaricity, Z=-1000


def _driver_source():
    sets = ",".join(f'"{k}" => :{v}' for k, v in COEFFICIENT_SETS.items())
    return (
        r"""# Auto-generated by _build_seawaterpolynomials_julia.py. Do not edit.
import Pkg
# Use a dedicated project env (gitignored) so we don't touch -- or depend on the
# integrity of -- the user's global Julia environment.
Pkg.activate(joinpath(@__DIR__, "_julia_env"); io=devnull)
for p in ("SeawaterPolynomials", "JSON")
    try
        @eval import $(Symbol(p))
    catch
        Pkg.add(p; io=devnull)
        @eval import $(Symbol(p))
    end
end
using SeawaterPolynomials: ρ, thermal_sensitivity, haline_sensitivity, RoquetEquationOfState
"""
        + r"""
function eval_grid(eos, S, T, Pdbar)
    rho = Float64[]; al = Float64[]; be = Float64[]
    for i in eachindex(S)
        Z = -Pdbar[i]                       # geopotential height [m] ~ -(sea pressure dbar)
        r = ρ(T[i], S[i], Z, eos)
        # NB: SeawaterPolynomials' SecondOrder `thermal_sensitivity`/`haline_sensitivity`
        # both return the *positive* partial derivative (= ∂ρ/∂Θ, ∂ρ/∂Sᴬ), i.e. xeos's
        # drho_dt / drho_ds -- despite the package's interface docstring calling the
        # thermal one -∂ρ/∂Θ. So alpha = -drho_dt/ρ negates the thermal sensitivity.
        a = thermal_sensitivity(T[i], S[i], Z, eos)   # = +∂ρ/∂Θ  (= xeos drho_dt)
        b = haline_sensitivity(T[i], S[i], Z, eos)    # = +∂ρ/∂Sᴬ (= xeos drho_ds)
        push!(rho, r); push!(al, -a / r); push!(be, b / r)
    end
    return Dict("rho" => rho, "alpha" => al, "beta" => be)
end

# self-check gates (published Table-3 coefficients) before emitting any truth
lin = RoquetEquationOfState(:Linear; reference_density=1024.6)
@assert abs(ρ(10.0, 35.0, 0.0, lin) - %CHECK_LIN%) < 1e-9 "Linear check failed: $(ρ(10.0,35.0,0.0,lin))"
cab = RoquetEquationOfState(:CabbelingThermobaricity; reference_density=1024.6)
@assert abs(ρ(10.0, 35.0, -1000.0, cab) - %CHECK_CAB%) < 1e-9 "CabThermo check failed: $(ρ(10.0,35.0,-1000.0,cab))"

input = JSON.parse(read(stdin, String))
S = Float64.(input["s"]); T = Float64.(input["t"]); P = Float64.(input["p_dbar"])
"""
        + f"""
sets = Dict({sets})
out = Dict{{String,Any}}()
for (eosid, sym) in sets
    eos = RoquetEquationOfState(sym; reference_density=1024.6)
    out[eosid] = eval_grid(eos, S, T, P)
end
print(JSON.json(out))
"""
    )


def julia_version():
    try:
        v = subprocess.run(["julia", "--version"], capture_output=True, text=True)
        return v.stdout.strip() or None
    except OSError:
        return None


def seawaterpolynomials_truth(s, t, p_dbar):
    """Return ``{backend_id: {rho, alpha, beta}}`` for the six idealized Roquet
    forms, evaluated by SeawaterPolynomials.jl, or None if julia is unavailable.
    Self-checks two published Table-3 values before trusting any output."""
    if julia_version() is None:
        return None
    src = (
        _driver_source()
        .replace("%CHECK_LIN%", repr(_CHECK_LINEAR_Z0))
        .replace("%CHECK_CAB%", repr(_CHECK_CABTHERMO_Zm1000))
    )
    with open(_DRIVER, "w") as fh:
        fh.write(src)
    payload = json.dumps({"s": list(s), "t": list(t), "p_dbar": list(p_dbar)})
    out = subprocess.run(
        ["julia", _DRIVER], input=payload, capture_output=True, text=True, check=True
    )
    return json.loads(out.stdout)
