"""Sphinx extension: auto-generate the model-selector -> EOS table.

Writes ``docs/_generated/selector_table.md`` from ``xeos``'s live selector
registry at build time, so the documentation can never drift from the code.
The table is pulled into ``usage.md`` with a MyST ``{include}`` directive.

The generator prefers a public ``xeos.selector_table()`` helper if one exists
(it yields ``(model, selector, eos_id)`` rows); otherwise it falls back to the
``xeos.MODEL_SELECTORS`` mapping, which is always present.
"""

from __future__ import annotations

import os


def _rows():
    """Yield ``(model, selector, eos_id)`` rows from xeos, sorted stably."""
    import xeos

    table = getattr(xeos, "selector_table", None)
    if callable(table):
        rows = list(table())
    else:
        rows = [
            (model, selector, eos_id)
            for model, selectors in xeos.MODEL_SELECTORS.items()
            for selector, eos_id in selectors.items()
        ]
    # Group by model (first appearance order), selectors alphabetical within.
    model_order = {}
    for model, _selector, _eos in rows:
        model_order.setdefault(model, len(model_order))
    return sorted(rows, key=lambda r: (model_order[r[0]], r[1]))


def _render_markdown(rows) -> str:
    lines = [
        "<!-- AUTO-GENERATED by docs/_ext/gen_selector_table.py — do not edit. -->",
        "",
        "| Model | Selector string | Canonical EOS id |",
        "| ----- | --------------- | ---------------- |",
    ]
    for model, selector, eos_id in rows:
        lines.append(f"| {model} | `{selector}` | `{eos_id}` |")
    lines.append("")
    return "\n".join(lines)


def _write_table(app):
    """``builder-inited`` handler: emit the generated Markdown table."""
    srcdir = app.srcdir
    out_dir = os.path.join(srcdir, "_generated")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "selector_table.md")
    content = _render_markdown(_rows())
    # Only rewrite when changed, to avoid needless rebuilds.
    try:
        with open(out_path, "r", encoding="utf-8") as fh:
            if fh.read() == content:
                return
    except FileNotFoundError:
        pass
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(content)


def setup(app):
    app.connect("builder-inited", _write_table)
    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
